# Generated by Django 4.1 on 2022-08-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task3Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players')),
            ],
        ),
        migrations.CreateModel(
            name='Task2Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players')),
            ],
        ),
        migrations.CreateModel(
            name='Task1Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players')),
            ],
        ),
    ]
