# Generated by Django 4.0.6 on 2022-08-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0002_task1text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task1text',
            old_name='player_id',
            new_name='player',
        ),
    ]
