# Generated by Django 4.0.6 on 2022-08-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0004_task3text_task2text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1text',
            name='time_added',
        ),
    ]
