# Generated by Django 4.0.5 on 2022-08-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0005_remove_task1text_time_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task2text',
            name='time_added',
        ),
        migrations.RemoveField(
            model_name='task3text',
            name='time_added',
        ),
        migrations.AlterField(
            model_name='task1text',
            name='player',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players'),
        ),
        migrations.AlterField(
            model_name='task2text',
            name='player',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players'),
        ),
        migrations.AlterField(
            model_name='task3text',
            name='player',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players'),
        ),
    ]
