# Generated by Django 4.0.5 on 2022-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0006_remove_task2text_time_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='Name')),
                ('product_desc', models.CharField(max_length=150, verbose_name='Description')),
                ('product_price', models.PositiveIntegerField(verbose_name='Price')),
            ],
        ),
    ]
