# Generated by Django 4.0.5 on 2022-08-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0007_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
