# Generated by Django 4.0.5 on 2022-08-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0008_alter_marketplace_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1text',
            name='earnedPoints',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='task2text',
            name='earnedPoints',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='task3text',
            name='earnedPoints',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Points'),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnedPoints', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True, verbose_name='Points')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players')),
            ],
        ),
    ]
