# Generated by Django 4.0.5 on 2022-08-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0009_task1text_earnedpoints_task2text_earnedpoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='earnedPoints',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='task1text',
            name='earnedPoints',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='task2text',
            name='earnedPoints',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='task3text',
            name='earnedPoints',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Points'),
        ),
    ]
