# Generated by Django 4.0.5 on 2022-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0010_alter_points_earnedpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1text',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
