# Generated by Django 4.0.5 on 2022-08-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0012_remove_task1text_time_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Leaderboard',
        ),
    ]
