# Generated by Django 4.0.5 on 2022-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0013_rename_points_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
