# Generated by Django 4.0.5 on 2022-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0014_leaderboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
