# Generated by Django 4.0.5 on 2022-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0021_players_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='players',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
