# Generated by Django 4.0.5 on 2022-08-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0022_alter_players_email_alter_players_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1text',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task3text',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
