# Generated by Django 4.0.5 on 2022-08-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0023_task1text_time_added_task3text_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='task2text',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
