# Generated by Django 4.0.5 on 2022-08-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0025_alter_task1proof_proof_orderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
