# Generated by Django 4.0.5 on 2022-08-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0026_orderdata_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderData',
        ),
    ]
