# Generated by Django 4.0.5 on 2022-08-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0027_delete_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(blank=True, max_length=100, null=True)),
                ('productid', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('productPrice', models.CharField(max_length=10)),
                ('deliveryAddress', models.CharField(blank=True, max_length=300, null=True)),
                ('contactNum', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ritu_web_app.players')),
            ],
        ),
    ]
