# Generated by Django 4.0.5 on 2022-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0030_messages_alter_players_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='players',
            name='picture',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task1proof',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='task1/'),
        ),
        migrations.AlterField(
            model_name='task2proof',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='task2/'),
        ),
        migrations.AlterField(
            model_name='task3proof',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='task3/'),
        ),
    ]
