# Generated by Django 4.0.5 on 2022-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0031_alter_marketplace_product_img_alter_players_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='earnedPoints',
            field=models.FloatField(blank=True, null=True, verbose_name='Points'),
        ),
    ]
