# Generated by Django 4.0.5 on 2022-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0032_alter_leaderboard_earnedpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='earnedPoints',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Points'),
        ),
    ]
